// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: llm_request.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *LLMInit) Reset() {
	*x = LLMInit{}
	mi := &file_llm_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMInit) ProtoMessage() {}

func (x *LLMInit) ProtoReflect() protoreflect.Message {
	mi := &file_llm_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMInit.ProtoReflect.Descriptor instead.
func (*LLMInit) Descriptor() ([]byte, []int) {
	return file_llm_request_proto_rawDescGZIP(), []int{0}
}

func (x *LLMInit) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMInit) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type LLMInference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *LLMInference) Reset() {
	*x = LLMInference{}
	mi := &file_llm_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMInference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMInference) ProtoMessage() {}

func (x *LLMInference) ProtoReflect() protoreflect.Message {
	mi := &file_llm_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMInference.ProtoReflect.Descriptor instead.
func (*LLMInference) Descriptor() ([]byte, []int) {
	return file_llm_request_proto_rawDescGZIP(), []int{1}
}

func (x *LLMInference) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_llm_request_proto protoreflect.FileDescriptor

var file_llm_request_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x6c, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6c, 0x6c, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x39, 0x0a, 0x07, 0x4c, 0x4c, 0x4d, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x4c,
	0x4c, 0x4d, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x32, 0x50, 0x0a, 0x0e, 0x41, 0x73, 0x6b, 0x4c, 0x4c, 0x4d, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x4c,
	0x4c, 0x4d, 0x12, 0x14, 0x2e, 0x6c, 0x6c, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x4c, 0x4c, 0x4d, 0x49, 0x6e, 0x69, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x6c, 0x6d, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x4c, 0x4d, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_llm_request_proto_rawDescOnce sync.Once
	file_llm_request_proto_rawDescData = file_llm_request_proto_rawDesc
)

func file_llm_request_proto_rawDescGZIP() []byte {
	file_llm_request_proto_rawDescOnce.Do(func() {
		file_llm_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_llm_request_proto_rawDescData)
	})
	return file_llm_request_proto_rawDescData
}

var file_llm_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llm_request_proto_goTypes = []any{
	(*LLMInit)(nil),      // 0: llm_request.LLMInit
	(*LLMInference)(nil), // 1: llm_request.LLMInference
}
var file_llm_request_proto_depIdxs = []int32{
	0, // 0: llm_request.AskLLMQuestion.PromptLLM:input_type -> llm_request.LLMInit
	1, // 1: llm_request.AskLLMQuestion.PromptLLM:output_type -> llm_request.LLMInference
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_request_proto_init() }
func file_llm_request_proto_init() {
	if File_llm_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_llm_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_request_proto_goTypes,
		DependencyIndexes: file_llm_request_proto_depIdxs,
		MessageInfos:      file_llm_request_proto_msgTypes,
	}.Build()
	File_llm_request_proto = out.File
	file_llm_request_proto_rawDesc = nil
	file_llm_request_proto_goTypes = nil
	file_llm_request_proto_depIdxs = nil
}
