// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: llm_request.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AskLLMQuestion_PromptLLM_FullMethodName = "/llm_request.AskLLMQuestion/PromptLLM"
)

// AskLLMQuestionClient is the client API for AskLLMQuestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AskLLMQuestionClient interface {
	PromptLLM(ctx context.Context, in *LLMInit, opts ...grpc.CallOption) (*LLMInference, error)
}

type askLLMQuestionClient struct {
	cc grpc.ClientConnInterface
}

func NewAskLLMQuestionClient(cc grpc.ClientConnInterface) AskLLMQuestionClient {
	return &askLLMQuestionClient{cc}
}

func (c *askLLMQuestionClient) PromptLLM(ctx context.Context, in *LLMInit, opts ...grpc.CallOption) (*LLMInference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMInference)
	err := c.cc.Invoke(ctx, AskLLMQuestion_PromptLLM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AskLLMQuestionServer is the server API for AskLLMQuestion service.
// All implementations must embed UnimplementedAskLLMQuestionServer
// for forward compatibility.
type AskLLMQuestionServer interface {
	PromptLLM(context.Context, *LLMInit) (*LLMInference, error)
	mustEmbedUnimplementedAskLLMQuestionServer()
}

// UnimplementedAskLLMQuestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAskLLMQuestionServer struct{}

func (UnimplementedAskLLMQuestionServer) PromptLLM(context.Context, *LLMInit) (*LLMInference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromptLLM not implemented")
}
func (UnimplementedAskLLMQuestionServer) mustEmbedUnimplementedAskLLMQuestionServer() {}
func (UnimplementedAskLLMQuestionServer) testEmbeddedByValue()                        {}

// UnsafeAskLLMQuestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AskLLMQuestionServer will
// result in compilation errors.
type UnsafeAskLLMQuestionServer interface {
	mustEmbedUnimplementedAskLLMQuestionServer()
}

func RegisterAskLLMQuestionServer(s grpc.ServiceRegistrar, srv AskLLMQuestionServer) {
	// If the following call pancis, it indicates UnimplementedAskLLMQuestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AskLLMQuestion_ServiceDesc, srv)
}

func _AskLLMQuestion_PromptLLM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLMInit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskLLMQuestionServer).PromptLLM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AskLLMQuestion_PromptLLM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskLLMQuestionServer).PromptLLM(ctx, req.(*LLMInit))
	}
	return interceptor(ctx, in, info, handler)
}

// AskLLMQuestion_ServiceDesc is the grpc.ServiceDesc for AskLLMQuestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AskLLMQuestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm_request.AskLLMQuestion",
	HandlerType: (*AskLLMQuestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PromptLLM",
			Handler:    _AskLLMQuestion_PromptLLM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm_request.proto",
}
